### ISSUE TITLE
Missing Dependencies -- zlib

### ISSUE THREAD

**Issue by erunks** [stumpycr/stumpy_png#13]
This is my main code:
```
require "stumpy_core"
require "stumpy_png"

p "test"
```
and this is what the terminal is saying:
```
/usr/bin/ld: cannot find -lz
collect2: error: ld returned 1 exit status
```

> From IRC (bridge bot) @FromIRC 12:39
> BlaXpirit: @erunks, install zlib
> 
> erunks @erunks 12:41
> I'm assuming that zlib isn't a standard package, do you know what dependency I'd need to apt-get install that?
> 
> From IRC (bridge bot) @FromIRC 12:41
> BlaXpirit: search engines know
> 
> Elthariel @elthariel 12:41
> @mverzilli : I've created a page for your future notes on the work on thread support : https://github.com/crystal-lang/crystal/wiki/Threads-support.
> I've also added build instructions, as it's not straightforward
> I might be doing something wrong as the specs seems to pass 
> 
> MatthewBennington @MatthewBennington 12:45
> @erunks zlib is a very common package. Here is the first result for a google search "ubuntu install zlib" https://askubuntu.com/questions/508934/how-to-install-libpng-and-zlib
> 
> erunks @erunks 12:46
> Wow. I'm surprised that needing an additional package like that wasn't stated in the readMe. I though mtools was what I needed for the longest times after searching around
> But I got it now. Thanks guys
> 
> MatthewBennington @MatthewBennington 12:48
> It's a common package, so the creators probably assumed it would already be installed. You should probably open an issue about this.
> 
> erunks @erunks 12:49
> Good point. I'll do that

Not necessarily an issue anymore, but wanted to bring this to light

**Comment by l3kn** [comment]
Thanks, I'll add a note to the readme.
Let me know if you run into any other problems
