### ISSUE TITLE
Getting an error when using version: "4.1.2" in shard.yml

### ISSUE THREAD

**Issue by JWeeb** [stumpycr/stumpy_png#14]
When calling 'shards install' with version: 4.1.2 in shard.yml, I get this error:

`
Error resolving stumpy_png (~> 4.1.2)
`

 I can install 4.1.1 with no problem.

Tried it on both Mac High Sierra (10.13.2) and Yosemite (10.10)

**Comment by l3kn** [comment]
Good catch, that's a typo in the readme,
it should say `4.2.1`.

Let me know if that works, I'll change it

**Comment by JWeeb** [comment]
Works great! Thanks so much!
