### ISSUE TITLE
8 bit depth saving is broken after 4.4.0

### ISSUE THREAD

**Issue by Michionlion** [stumpycr/stumpy_png#20]
I'm not sure if `4.4.0` broke something or I'm doing something wrong after a breaking change, but after `4.4.0` something is seriously wrong with 8 bit output. I'm getting completely different output when drawing basic shapes -- it seems that something has changed or was broken with the encoding. I've included a spec below. Just include that in a project and switch versions from 4.3 to 4.4, as well as changing the `bit_depth` saved at.

```
require "stumpy_png"
require "spec"

class Graphic
  include StumpyPNG

  enum MixMode
    Linear
    Alpha
    Multiply
    None
  end

  getter canvas : Canvas

  getter color : RGBA = RGBA::WHITE
  property mixing : MixMode = MixMode::Alpha

  getter size : Tuple(Float64, Float64)

  def initialize(@size)
    @canvas = Canvas.new size[0].round.to_i, size[1].round.to_i, RGBA.from_hex("#00000000")
  end

  def color=(new_color : RGBA)
    @color = new_color
  end

  # Naive circle drawing algorithm
  def circle(x : Number, y : Number, radius : Number)
    start_x = (x - radius).floor.to_i
    end_x = (x + radius).ceil.to_i
    start_y = (y - radius).floor.to_i
    end_y = (y + radius).ceil.to_i

    (start_x..end_x).each do |cx|
      (start_y..end_y).each do |cy|
        fill cx, cy if (cx - start_x - radius.ceil.to_i)**2 + (cy - start_y - radius.ceil.to_i)**2 <= radius**2 * 0.8
      end
    end
  end

  def fill(x, y, with new_color = color)
    # puts "safe pixel at #{x}, #{y}"
    mixed = mix new_color, x, y
    canvas.safe_set x, y, mixed
  end

  private def mix(new_color, x, y, keep_old_percent = 0.5)
    return new_color if canvas.safe_get(x, y).nil?

    case mixing
    when MixMode::Alpha    then new_color.over canvas.safe_get(x, y).as(RGBA)
    when MixMode::Linear   then new_color.mix canvas.safe_get(x, y).as(RGBA), keep_old_percent
    when MixMode::Multiply then new_color.multiply canvas.safe_get(x, y).as(RGBA)
    else                        new_color
    end
  end
end



describe "circle test" do
  it "draws a bunch of circles" do
    graphic = Graphic.new({1310.0, 32.0})

    graphic.color = StumpyPNG::RGBA::BLUE

    x = 5
    0.step to: 100 do |radius10|
      radius = radius10 / 10.0
      graphic.circle x.round.to_i, 16, radius
      graphic.fill x.round.to_i, 16, StumpyPNG::RGBA.from_relative(1, 1, 1, 0.4) if radius > 2
      x += radius * 2 + 3
    end

    StumpyPNG.write graphic.canvas, "circle_test.png", bit_depth: 8
  end
end
```

**Comment by r00ster91** [comment]
Damn sorry for that! :(
It surely happens because of changes in this file: https://github.com/stumpycr/stumpy_png/pull/19/files#diff-1faabda48ccb57e7fd49423d3c44c58a. Can you please test if changing [this](https://github.com/stumpycr/stumpy_png/blob/ee75cfd4a13a7e2e76ab4f87259f971eb483f4a1/src/stumpy_png.cr#L197) line back to `encode(gray.to_u16, buffer_ptr)` and adding this method:
```crystal
  private def self.encode(value : UInt16, slice)
    bytes = pointerof(value).as(UInt8[2]*).value
    slice[0] = bytes[1]
    slice[1] = bytes[0]
  end
```
fixes your issue?
You can simply change the code of stumpy_png in the lib folder.

**Comment by Michionlion** [comment]
That sadly did not fix the issue, but PR #21 does! Good work :)

**Comment by l3kn** [comment]
Nice, thanks for fixing the problem so quickly @r00ster91!
I'll merge the PR to get things working again and take a look at the code tomorrow.

**Comment by l3kn** [comment]
@r00ster91 `each_with_index(1)` was a good idea,
but the value for `i` is incremented in the inner loop (line 124)
`{pixel.r, pixel.g, pixel.b, pixel.a}.each`.

Ideally the test suite should catch errors like that,
I'll add test cases for the different bit depths.
