### ISSUE TITLE
Build fails on latest crystal version

### ISSUE THREAD

**Issue by bararchy** [stumpycr/stumpy_png#24]
```
In lib/stumpy_png/src/stumpy_png/scanline.cr:50:24

 50 | byte = scanline[x / 8]
                     ^
Error: no overload matches 'Slice(UInt8)#[]' with type Float64

Overloads are:
 - Slice(T)#[](start : Int, count : Int)
 - Slice(T)#[](range : Range)
 - Indexable(T)#[](index : Int)
```

**Comment by oprypin** [comment]
It's the integer division. Needs to be `x // 8`

**Comment by l3kn** [comment]
It's been a while since I've worked with crystal, can someone take a look at my pull request https://github.com/stumpycr/stumpy_png/pull/25?

The test suite passes, but there might be a better way to fix the problems.

**Comment by bararchy** [comment]
@l3kn I belive #25 is good to go, shell we merge?

**Comment by l3kn** [comment]
Done, thank for the help!

The `stumpy_utils` test suite is failing, too.
I'll take a look at that tomorrow.

**Comment by bararchy** [comment]
@l3kn I think it's because of: https://github.com/l3kn/pcf-parser/issues/1
