### ISSUE TITLE
Question about security and memory safety

### ISSUE THREAD

**Issue by ndbroadbent** [stumpycr/stumpy_png#26]
Hello! I'm thinking about porting my Rails app to Crystal/Lucky, and I need to do some image processing. I'm wondering how safe the stumpy image libraries are, compared to a library written in C? Does Crystal have much better memory safety?

I skimmed through some of the stumpy_png source code, and the code is really nice and easy to read! But does stumpy_png protect against things like [decompression bombs](http://www.aerasec.de/security/advisories/decompression-bomb-vulnerability.html)? And is it possible to enumerate all of the places where it's possible to crash? (And has anyone performed any fuzzing or static analysis?)

I know that Crystal doesn't protect against integer overflow, so I could see a few places in the source code where that might be possible, but I guess that would just result in an invalid image. 

I also couldn't see any cases where it might be possible to divide by zero. So I would just like to know more about the potential for decompression bombs, and also what kind of crashes I should be prepared to handle? (Or is it theoretically impossible for this library to crash with an error or segfault?)

**Comment by l3kn** [comment]
Hi!

As an attacker, I would craft a png image with an IHDR header with width and height set to 2^32-1
and no data chunks.
This library would then try to create a blank `Canvas` object of size (2^32 - 1) * (2^32 -1), probably using up all of the systems memory.

Unlike the examples in your link, the image would not even need any data chunks, resulting in a huge expansion ratio.

To protect against this, you could change the `parse_IHDR` function to raise an error if the image size is greater than some limit.

I haven't done any crystal programming in the past few month.
@redcodefinal: I saw you're doing some IT-security related projects, do you have any other concerns?

**Comment by redcodefinal** [comment]
Honestly these kinds of attacks are out of my range of expertise but, from my understanding, the really bad attacks aren't applicable to Crystal unless you use unsafe memory/C extensions. Worse case it seems they crash the program, but still, DoS is no joke. There's probably a good way to handle this safely, to ensure if there is a crash in stumpy to handle it gracefully. Otherwise I looked through the code and didn't see anything that immediately jumped out at me and said "this is dangerous".
