### ISSUE TITLE
Set SHARDS_OPTS=--ignore-crystal-version on Travis CI

### ISSUE THREAD

**Issue by Sija** [stumpycr/stumpy_png#34]
![image](https://user-images.githubusercontent.com/988/91670304-6edfe500-eb1c-11ea-83cd-1069514dc658.png)

Otherwise `nightly` builds will be failing, as they do now.

**Comment by oprypin** [comment]
You can just specify <code>crystal: "<b>>=</b> 0.35.1"</code> instead.

No idea why that's not being advertised as the solution, but egh none of that made sense to me

**Comment by l3kn** [comment]
I've added the environment variable, the nighly build is passing now.

@oprypin Where would that go? In the shard.yml?
If you think it's a better solution, we can change it.

**Comment by oprypin** [comment]
https://github.com/stumpycr/stumpy_png/blob/9a7399a27f0e3b710cb7c2be699649c6c276b27e/shard.yml#L17

**Comment by Sija** [comment]
@l3kn Great! Closing the since the issue at hand has been resolved.
